export interface DoctorRole {
  value: string;
  label: string;
}

export const doctorRoles: DoctorRole[] = [
  { value: "Interne en médecine", label: "Interne en médecine" },
  { value: "Chef de service", label: "Chef de service" },
  { value: "Praticien hospitalier (PH)", label: "Praticien hospitalier (PH)" },
  { value: "Praticien hospitalier temps partiel", label: "Praticien hospitalier temps partiel" },
  { value: "Chef de clinique - Assistant des hôpitaux", label: "Chef de clinique - Assistant des hôpitaux" },
  { value: "Assistant hospitalier", label: "Assistant hospitalier" },
  { value: "Médecin contractuel", label: "Médecin contractuel" },
  { value: "Praticien associé", label: "Praticien associé" },
  { value: "Praticien adjoint contractuel (PAC)", label: "Praticien adjoint contractuel (PAC)" },
  { value: "Médecin libéral", label: "Médecin libéral" },
  { value: "Médecin libéral secteur 1", label: "Médecin libéral secteur 1" },
  { value: "Médecin libéral secteur 2", label: "Médecin libéral secteur 2" },
  { value: "Collaborateur libéral", label: "Collaborateur libéral" },
  { value: "Médecin remplaçant", label: "Médecin remplaçant" },
  { value: "Associé de cabinet médical", label: "Associé de cabinet médical" },
  { value: "Praticien à exercice mixte", label: "Praticien à exercice mixte" },
  { value: "Directeur médical", label: "Directeur médical" },
  { value: "Chef de pôle", label: "Chef de pôle" },
  { value: "Président(e) de CME", label: "Président(e) de CME" },
  { value: "Responsable qualité et gestion des risques", label: "Responsable qualité et gestion des risques" },
  { value: "Coordonnateur médical", label: "Coordonnateur médical" },
  { value: "Professeur des universités - Praticien hospitalier (PU-PH)", label: "Professeur des universités - Praticien hospitalier (PU-PH)" },
  { value: "Maître de conférences des universités", label: "Maître de conférences des universités" },
  { value: "Professeur associé", label: "Professeur associé" },
  { value: "Chercheur clinicien", label: "Chercheur clinicien" },
  { value: "Investigateur principal", label: "Investigateur principal" },
  { value: "Expert judiciaire", label: "Expert judiciaire" },
  { value: "Médecin conseil", label: "Médecin conseil" },
  { value: "Médecin expert", label: "Médecin expert" },
  { value: "Consultant médical", label: "Consultant médical" },
  { value: "Auditeur médical", label: "Auditeur médical" },
  { value: "Médecin dans l'industrie pharmaceutique", label: "Médecin dans l'industrie pharmaceutique" },
  { value: "Directeur médical industriel", label: "Directeur médical industriel" },
  { value: "Chargé d'affaires médicales", label: "Chargé d'affaires médicales" },
  { value: "Médecin inspecteur de santé publique", label: "Médecin inspecteur de santé publique" },
  { value: "Médecin conseiller technique", label: "Médecin conseiller technique" },
  { value: "Directeur d'hôpital", label: "Directeur d'hôpital" },
  { value: "Médecin humanitaire", label: "Médecin humanitaire" },
  { value: "Médecin militaire", label: "Médecin militaire" },
  { value: "Médecin scolaire", label: "Médecin scolaire" },
  { value: "Médecin de PMI", label: "Médecin de PMI" },
  { value: "Médecin pénitentiaire", label: "Médecin pénitentiaire" },
  { value: "Médecin sapeur-pompier", label: "Médecin sapeur-pompier" },
  { value: "Médecin du sport", label: "Médecin du sport" },
  { value: "Médecin thermal", label: "Médecin thermal" },
  { value: "Médecin urgentiste", label: "Médecin urgentiste" },
  { value: "Médecin SAMU", label: "Médecin SAMU" },
  { value: "Médecin SMUR", label: "Médecin SMUR" },
  { value: "Médecin régulateur", label: "Médecin régulateur" },
  { value: "Médecin DIM", label: "Médecin DIM" },
  { value: "Praticien en hygiène hospitalière", label: "Praticien en hygiène hospitalière" },
  { value: "Référent antibiotiques", label: "Référent antibiotiques" },
  { value: "Responsable des vigilances", label: "Responsable des vigilances" },
  { value: "Secrétaire général d'organisation médicale", label: "Secrétaire général d'organisation médicale" },
  { value: "Président de syndicat médical", label: "Président de syndicat médical" },
  { value: "Membre du conseil de l'ordre", label: "Membre du conseil de l'ordre" },
  { value: "Médecin télésanté", label: "Médecin télésanté" },
  { value: "Médecin spécialiste données de santé", label: "Médecin spécialiste données de santé" },
  { value: "Médecin innovation et transformation digitale", label: "Médecin innovation et transformation digitale" },
  { value: "Entrepreneur médical", label: "Entrepreneur médical" },
  { value: "Médecin retraité actif", label: "Médecin retraité actif" },
  { value: "Médecin bénévole", label: "Médecin bénévole" },
  { value: "Médecin coopérant", label: "Médecin coopérant" },
  { value: "Médecin détaché", label: "Médecin détaché" }
]; 