export const specialties = [
  { value: "Médecine générale", label: "Médecine générale" },
  { value: "Chirurgie générale", label: "Chirurgie générale" },
  { value: "Chirurgie orthopédique et traumatologie", label: "Chirurgie orthopédique et traumatologie" },
  { value: "Chirurgie cardiovasculaire", label: "Chirurgie cardiovasculaire" },
  { value: "Chirurgie thoracique", label: "Chirurgie thoracique" },
  { value: "Chirurgie viscérale et digestive", label: "Chirurgie viscérale et digestive" },
  { value: "Chirurgie plastique reconstructrice et esthétique", label: "Chirurgie plastique reconstructrice et esthétique" },
  { value: "Chirurgie vasculaire", label: "Chirurgie vasculaire" },
  { value: "Neurochirurgie", label: "Neurochirurgie" },
  { value: "Chirurgie pédiatrique", label: "Chirurgie pédiatrique" },
  { value: "Urologie", label: "Urologie" },
  { value: "Chirurgie maxillo-faciale", label: "Chirurgie maxillo-faciale" },
  { value: "Cardiologie", label: "Cardiologie" },
  { value: "Dermatologie", label: "Dermatologie" },
  { value: "Endocrinologie-diabétologie-nutrition", label: "Endocrinologie-diabétologie-nutrition" },
  { value: "Gastro-entérologie et hépatologie", label: "Gastro-entérologie et hépatologie" },
  { value: "Gériatrie", label: "Gériatrie" },
  { value: "Hématologie", label: "Hématologie" },
  { value: "Médecine interne", label: "Médecine interne" },
  { value: "Néphrologie", label: "Néphrologie" },
  { value: "Neurologie", label: "Neurologie" },
  { value: "Oncologie médicale", label: "Oncologie médicale" },
  { value: "Pneumologie", label: "Pneumologie" },
  { value: "Rhumatologie", label: "Rhumatologie" },
  { value: "Médecine physique et de réadaptation", label: "Médecine physique et de réadaptation" },
  { value: "Psychiatrie", label: "Psychiatrie" },
  { value: "Pédopsychiatrie", label: "Pédopsychiatrie" },
  { value: "Addictologie", label: "Addictologie" },
  { value: "Pédiatrie", label: "Pédiatrie" },
  { value: "Néonatologie", label: "Néonatologie" },
  { value: "Gynécologie-obstétrique", label: "Gynécologie-obstétrique" },
  { value: "Gynécologie médicale", label: "Gynécologie médicale" },
  { value: "Ophtalmologie", label: "Ophtalmologie" },
  { value: "Oto-rhino-laryngologie", label: "Oto-rhino-laryngologie" },
  { value: "Anesthésie-réanimation", label: "Anesthésie-réanimation" },
  { value: "Médecine intensive-réanimation", label: "Médecine intensive-réanimation" },
  { value: "Radiologie et imagerie médicale", label: "Radiologie et imagerie médicale" },
  { value: "Médecine nucléaire", label: "Médecine nucléaire" },
  { value: "Anatomie et cytologie pathologiques", label: "Anatomie et cytologie pathologiques" },
  { value: "Biologie médicale", label: "Biologie médicale" },
  { value: "Médecine du travail", label: "Médecine du travail" },
  { value: "Santé publique", label: "Santé publique" },
  { value: "Médecine légale et expertises médicales", label: "Médecine légale et expertises médicales" },
  { value: "Médecine d'urgence", label: "Médecine d'urgence" },
  { value: "Génétique médicale", label: "Génétique médicale" },
  { value: "Médecine tropicale", label: "Médecine tropicale" },
  { value: "Allergologie", label: "Allergologie" },
  { value: "Médecine de la douleur", label: "Médecine de la douleur" },
  { value: "Médecine palliative", label: "Médecine palliative" },
  { value: "Médecine du sommeil", label: "Médecine du sommeil" },
  { value: "Médecine du sport", label: "Médecine du sport" },
  { value: "Odontologie", label: "Odontologie" },
  { value: "Orthodontie", label: "Orthodontie" },
  { value: "Chirurgie orale", label: "Chirurgie orale" },
  { value: "Médecine vétérinaire générale", label: "Médecine vétérinaire générale" },
  { value: "Médecine vétérinaire spécialisée", label: "Médecine vétérinaire spécialisée" }
]; 